### PR TITLE
Issue 77: Organise Tor Browser section in a more meaningful way

### PR DESCRIPTION
**Pull request by Angelvicks**
I edited the contents.lr and attribute a key value

### CODE REVIEW

**Review by LilyLME — COMMENTED** [review]
Hello @Angelvicks . Good work. Why did you include both a seo_slug and _slug

**Comment by Angelvicks** [comment]
Hello @LilyLME , am just following the examples i was giving and the contents.lr file i saw

**Comment by LilyLME** [comment]
> Hello @LilyLME , am just following the examples i was giving and the contents.lr file i saw

Oh okay. Was just wondering. I am also learning

**Comment by MacTavish-69** [comment]
Hi @Angelvicks @LilyLME I believe there is no need to add "_slug" Since it is not defined anywhere in the relevant models.

**Comment by Angelvicks** [comment]
I will  remove the _slug then.

**Comment by MacTavish-69** [comment]
@Angelvicks I believe you can ignore it for now. Since  _slug is not defined so it won't have an effect.

**Comment by Angelvicks** [comment]
Ok thanks @Mac000

**Pull request closed without merging**
