### PR TITLE
updated the URL bar Onion indicators on the documentation page

### PR DESCRIPTION
**Pull request by Goodiec**
I updated the URL bar Onion indicators as requested here - https://gitlab.torproject.org/torproject/web/support/issues/94, please review

### CODE REVIEW

**Comment by holantonela-zz** [comment]
Hi! I'm reviewing the commit a33fcf6.
 
I think we should use "gray" instead of "black" because is the color the icon will be rendered at the UI. 

Also, the description of the cases for each icon is fine. We may want to add a paragraph explaining what is secure and what not and what are the trade-offs.

See how Firefox handled this question: https://support.mozilla.org/en-US/kb/how-do-i-tell-if-my-connection-is-secure

**Comment by gusgustavo** [comment]
Your pull request also included Snowflakes questions, could you remove it?

**Comment by Goodiec** [comment]
> Your pull request also included Snowflakes questions, could you remove it?

Yes, I'm having a hard time doing that, could you please tell me how to do that. I also have a pull request open for just the Snowflake questions

**Comment by Goodiec** [comment]
> Hi! I'm reviewing the commit [a33fcf6](https://github.com/torproject/support/commit/a33fcf62794cfa977e8d4ff278567370790dd909).
> 
> I think we should use "gray" instead of "black" because is the color the icon will be rendered at the UI.
> 
> Also, the description of the cases for each icon is fine. We may want to add a paragraph explaining what is secure and what not and what are the trade-offs.
> 
> See how Firefox handled this question: https://support.mozilla.org/en-US/kb/how-do-i-tell-if-my-connection-is-secure

Ok, so should I change them to gray?

**Comment by holantonela-zz** [comment]
Yes, you should.

**Comment by Goodiec** [comment]
> Yes, you should.

Ok, I will

**Pull request closed without merging**
