### PR TITLE
Updates screengrabs in /static/images folder

### PR DESCRIPTION
**Pull request by SehrishHussain**
Updated the screengrabs on both pages as mentioned in Gitlab [issue](https://gitlab.torproject.org/tpo/web/support/-/issues/170)

@gusgustavo and @championquizzer  take a look at this PR

Note: I figured to make changes and push it to github on my old machine.

### CODE REVIEW

**Comment by SehrishHussain** [comment]
can you review these changes @gusgustavo

**Comment by gusgustavo** [comment]
1. You don't need to change this screenshot: https://support.torproject.org/static/images/menu-new-identity.png, so please keep the original one.
2. Please remake this screenshot: https://support.torproject.org/static/images/new-circuit-display.png but with https://support.torproject.org website.  
3. The onion screenshot (/onionservices/onionservices-2/) seems right!
4. Fix the above items (1 and 2) and squash your commits or send a new pull request.

You're almost there!

**Comment by SehrishHussain** [comment]
@gusgustavo I have attempted to squash my commits. Please take a look.

@championquizzer mind reviewing my squash commits please let me know if it is right.

**Comment by championquizzer** [comment]
@SehrishHussain, just a few notes about squashing. There are still [two separate commits](https://github.com/torproject/support/pull/222/commits) in this PR. If squashed properly it should only have 1 commit (that's the point of squashing!) Hint: you need to `pick` the first commit and `squash` the other commit. The interactive rebase should look something like this:  
```
pick <commit id> previous-commit
squash <commit id> latest-commit
```
After this, you need to force push since at this point you have modified your git history.

**Comment by SehrishHussain** [comment]
@championquizzer Can you help?

**Pull request closed without merging**
