### PR TITLE
Capitalize and make singular 'Tor rpm packages'

### PR DESCRIPTION
**Pull request by nicoleiocana**
Concerning issue, https://gitlab.torproject.org/torproject/web/support/-/issues/110.

Fixed:

fixed-tor-rpm-packages

### CODE REVIEW

**Comment by nicoleiocana** [comment]
@hiromipaw When you are available, can you please review?

**Comment by gusgustavo** [comment]
Hi @nicoleiocana, could you change to "RPM Repository"? Since we have `Debian Repository`, we should keep the consistency.

**Comment by nicoleiocana** [comment]
@gusgustavo Change made.

**Comment by nicoleiocana** [comment]
This PR was combined and updated to this PR:
https://github.com/torproject/support/pull/149

**Pull request closed without merging**
