### PR TITLE
Improve verifying signature instructions

### PR DESCRIPTION
**Pull request by khelvn**
I tried to improve the verifying signature instructions by treating each OS users individually. I also replaced old links with current ones. I provided an alternate method in the case of errors.

### CODE REVIEW

**Comment by kulloveth** [comment]
> I tried to improve the verifying signature instructions by treating each OS users individually. I also replaced old links with current ones. I provided an alternate method in the case of errors.

hey @khelvn this does not work on my windows 10 and windows 8.1 would love to know which windows OS version you tested it on

**Comment by khelvn** [comment]
hey @kulloveth I tested it on windows 10, what exactly didn't work for you.

**Comment by khelvn** [comment]
I'm recreating this in a new branch, I provide the link for the new PR

**Comment by khelvn** [comment]
https://github.com/torproject/support/pull/135

**Pull request closed without merging**
