### PR TITLE
Added term search-engine to glossary list

### PR DESCRIPTION
**Pull request by Burnleydev1**
Added the term search-engine

### CODE REVIEW

**Review by gusgustavo — CHANGES_REQUESTED** [review]
Was this copied from here? https://moz.com/beginners-guide-to-seo/how-search-engines-operate
If you copy a phrase from another page, you need to quote correctly. Please rewrite this entry.

**Comment by Burnleydev1** [comment]
Hi @gusgustavo did reference from that site. new update has reference link

**Comment by gusgustavo** [comment]
I don't see any benefit in copying this definition and linking to Mozilla's website.

**Comment by Burnleydev1** [comment]
I did just as you said @gusgus. I thought you said i should do proper quoting or maybe I didn't get it well. Thanks

**Pull request closed without merging**
