### PR TITLE
Updated the latest screengrab for hamburger menu.

### PR DESCRIPTION
**Pull request by SehrishHussain**
Using latest release of TB 10.0.15 the screengrab of hamburger menu is updated. It is now showing the latest icons.

@championquizzer please review this PR.

### CODE REVIEW

**Comment by SehrishHussain** [comment]
@championquizzer please check the file. I have removed and replaced the image. However, it always keeps on showing the old image in Preview. I have checked it 3 to 4 times just to make sure. IMHO It's a bug in GitHub. Please check by removing and adding an image in file.

**Comment by SehrishHussain** [comment]
Here I have deleted the image from file.

oo




While in Preview it still shows the deleted image.

**Comment by championquizzer** [comment]
Hey @SehrishHussain. Thanks for working on this. I just saw the file changes in the commit and the screenshot you attached above. As Gus already mentioned here: https://gitlab.torproject.org/tpo/web/support/-/issues/170#note_2730613, you need to update the images in [`assets/static/images`](https://github.com/torproject/support/tree/master/assets/static/images) directory in the repo and not change the markdown file. fwiw, this GitHub repo is just a mirror and not the canonical location of the source code and introducing external urls (like `https://user-images.githubusercontent.com/66127574/113146393-0c350000-9249-11eb-95cf-ff85361608e4.png`) can break things.

**Comment by SehrishHussain** [comment]
@championquizzer thanks for making it clear. Now it's clear to me that I have to make changes in assets/static/images and not in markdown file. It wasn't fully clear earlier.

**Pull request closed without merging**
