### PR TITLE
adds note explaining that # is to run command as root user

### PR DESCRIPTION
**Pull request by luanafaustini**

### CODE REVIEW

**Comment by andinus** [comment]
> **Note:** Please note that the symbol # refers to be running the code as root. That means that you should have access to a user account with system administration privileges, e.g your user should be in the sudo group. 

It can be shortened to:

**Note:** The symbol # refers to be running the code as root. That means you should have access to a user account with system administration privileges, e.g your user should be in the sudo group.

**Comment by luanafaustini** [comment]
Changed!

**Comment by gusgustavo** [comment]
Could you also add the same note here: https://support.torproject.org/rpm/
Then we will merge.

**Comment by luanafaustini** [comment]
Done! @emmapeel2 gave the idea of putting also on the glossary. What do you think @gusgustavo ?

**Comment by gusgustavo** [comment]
It's a good idea, but I don't know how the glossary is working (if you should add to 'misc' or 'glossary' section). @emmapeel2 would you help @luanafaustini here?

**Comment by emmapeel2** [comment]
> Done! @emmapeel2 gave the idea of putting also on the glossary. What do you think @gusgustavo ?

yeah forget about it, it was a bad idea i think.. i am not sure how it will work if we call the folder '#' , etc.

**Pull request merged**
